#!/bin/bash
echo "Enter the input1"
read a
echo "Enter the input2"
read b
coa=$ (echo $a |wc -c)
cob=$ (echo $b |wc -c)
if [[ $coa -gt $cob ]]
then
ou="$a$b"
sum_of_chrt=$(($coa+$cob))
echo "Count of characters of inputs $a is greater then count of character of input $b and combined output  of $a and $b is $ou\n count of characters of $a and $b is $sum_of_chrt"
elif [[ $cob -gt $coa ]]
then
echo "Enter another user input"
read c
coc=$ (echo $c |wc -c)
ou="$a$b$c"
sum_di_chrt=$($coc-$cob+$coc)
echo -e "Count of characters of inputs $a is greater then count of character of input $b and combined output  of $a and $b and $c is $ou\n count of character in $a is $coa\n count of character in $b is $cob\n count of characters $a and $b and subtract $c is $sum_di_chrt"
elif [[ $coa -eq $cob ]]
then
echo "count of characters $a and $b is same"
if [[ $a == $b ]]
then
echo "Both  input $a and $b is same"
who -r
useradd $a
grep $a /etc/passwd  >/tmp/$a
groupadd $a
grep $a /etc/group >>/tmp/$a
echo "Verification of user and groups details"
cat /tmp/$a
elif [[ $a != $b ]]
then
echo "Enter the input to be checked in $a"
read con
col=$(echo $a |grep $con|wc -l)
if [[ $con -gt 0 ]]
then
echo "$con present in input $a"
else
echo "$con not present in input $a"
fi
fi
fi
